version: 2
updates:
- package-ecosystem: uv
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
  open-pull-requests-limit: 10
  reviewers:
  - stulacy
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  commit-message:
    prefix: "fix: "
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  commit-message:
    prefix: "fix: "
