name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    name: Python CI checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Black
      run: |
        uvx black src
    - name: Ruff
      run: |
        uvx ruff check src
    - name: Bandit
      run: |
        uvx bandit -r src
    - name: Install deps
      run: |
        uv sync --extra test
    - name: Unit tests
      run: |
        uvx pytest
    - name: Integration tests
      run: |
        uvx pytest -m 'integration'
    - name: Install full deps
      run: |
        uv sync --extra test --extra full
    - name: Unit tests of full deps
      run: |
        uvx pytest -m 'full and not integration'
    - name: Integration tests of full deps
      run: |
        uvx pytest -m 'full and integration'
