name: Publish to PyPI
on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cellphe
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Create venv
      run: |
        uv venv
    - name: Install build deps
      run: |
        uv pip install --upgrade build
    - name: Build package
      run: |
        uv run python -m build
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
